from passrotate.providers.amazon import Amazon
from passrotate.providers.digitalocean import DigitalOcean
from passrotate.providers.discord import Discord
from passrotate.providers.linode import Linode
from passrotate.providers.pixiv import Pixiv
from passrotate.providers.ycombinator import YCombinator
from passrotate.providers.zotero import Zotero
from passrotate.providers.pypi import PyPI
from passrotate.providers.ankiweb import AnkiWeb
from passrotate.providers.gitlab import GitLab
from passrotate.providers.aur import ArchUserRepository
from passrotate.providers.ao3 import Ao3
